Save num of changes to filename, update a lot of dependencies and fix compiling develop branch
kerberos-io/agent pull request #39
Opened 2022-08-17 18:35 UTC by olokos

**This is an updated version of #37 and #38 ** 

This is the first implementation of the recording data being sent as a metadata struct, so it could be applied to the output filename of the recording.

I have also updated a lot of go and javascript (yarn/npm) dependencies.

I made Dockerfile to use node16 - since it's the latest LTS supported version aswell as some other improvements.

Each commits has quite well described commit message

With this commit I'm also updating develop branch to the current code state in master, so there will be no issues later on when merging this.

There are no changes in the code I've made since #37 I just resolved the conflicts caused by adding another commit to the original develop branch and recreated the PR

2022-08-17 18:50 UTC, cedricve requested changes
amazing work @olokos, happy you made it. Can you verify below ideas? The pull request is still failing in your React code, you might need to add some more fixes. Happy to include your fixes afterwards! Well done ;)

2022-08-17 18:50 UTC, cedricve commented on machinery/src/components/Kerberos.go
> +		communication.HandleMotion = make(chan models.MotionDataPartial, 2)
@olokos why did you change the channel to size 2 ?

2022-08-17 18:50 UTC, cedricve commented on machinery/src/models/MotionData.go
> +type MotionDataFull struct {
Where is this used?

2022-08-17 19:59 UTC, olokos commented
The build on GH Actions was still failing because of a tiny semantic difference in 3debf6297591ac4d638e498e0a08093e2e45844e 
What's interesting is that it was not failing the build at all on a local filesystem with `yarn build` at all, but on actions it somehow did.
It wasn't really much of an issue, more of Eslint wanting the code to be perfect, preventing the build. Fixed in 87f84e993a249aea5bb14b6bee2e599083293866

2022-08-17 20:03 UTC, olokos commented on machinery/src/models/MotionData.go
> +type MotionDataFull struct {
Right now nowhere, as we're still missing a lot of input data to fill the filename completely.

For now I've created 2 models:
`MotionDataPartial` that has timestamp + amount of  changes
`MotionDataFull` that has everything, but as I couldn't find an easy and quick way to get the rest of data, I decided to leave it in there, despite it's not used anywhere else - it's ready for when somebody more experienced makes the rest of the filename work, at which point `MotionDataPartial` can be deleted and replaced with just `MotionData`

2022-08-17 20:05 UTC, olokos commented on machinery/src/components/Kerberos.go
> +		communication.HandleMotion = make(chan models.MotionDataPartial, 2)
`int64` is a single value, so channel size 1
`models.MotionDataPartial` is a struct consiting of timestamp and amount of changes, so there are 2 values to handle.

With `models.MotionDataFull` (when we get the rest of input data ready to insert there) we would have to correspondingly expand the channel with +1 for each new type of data being transferred.

2022-08-17 20:11 UTC, olokos commented on machinery/src/components/Kerberos.go
> +		communication.HandleMotion = make(chan models.MotionDataPartial, 2)
https://github.com/olokos/agent/blob/develop/machinery/src/computervision/main.go#L299
I also made FindMotion return 2 values, so this could be passed on to the channel and later filename, not sure if that's the best possible approach, but seems pretty clean to me.

2022-08-17 20:16 UTC, olokos commented
![image](https://user-images.githubusercontent.com/1755581/185234197-161e8840-612c-4add-ae6c-5241e930b7fb.png)

This 1kb recording save bug seems to be the last actual issue with this entire PR!

I expect the bug to be somewhere here:
https://github.com/kerberos-io/agent/pull/39/files#diff-ffdbf8bce9c0be9c74ac3d8965a566a7d26ec648b89d2a64cdce0122e96b03d0R279

I think this could be done better, but I'm not sure how.

Also @cedricve I highly suggest removing Codacy Static Code Analysis as 99% of the time it just fails without a good reason behind it, just like now.

2022-08-17 20:19 UTC, olokos commented
Also, since this is on develop branch, I think this PR can be already merged to develop already.

https://hub.docker.com/r/olokos/agent-olokos/tags
lastest build above or version 0.0.4.4 is 1:1 with this entire PR merged, including all of the improvements, if anybody wants to test

2022-08-17 20:27 UTC, cedricve commented on machinery/src/components/Kerberos.go
> +		communication.HandleMotion = make(chan models.MotionDataPartial, 2)
should be 1 actually for both, this is determining that it should block after the first request is handled. Upgrading to 2 might cause strange behaviours while restarting the agent etc.

2022-08-17 21:35 UTC, cedricve approved these changes
Bravo @olokos

2022-08-17 22:54 UTC, olokos commented
> Bravo @olokos

Thank You! Feel free to merge! :)

2022-08-18 08:21 UTC, merged

2022-08-18 08:21 UTC, cedricve commented
merged thank you @olokos